const express=require("express");
const c=require("../controllers/prestationController");
const {authenticate,optionalAuthenticate}=require("../middlewares/authMiddleware");
const {upload,setUploadFolder}=require("../middlewares/uploadMiddleware");
const router=express.Router();
const catUpload=[setUploadFolder("uploads/categorie_images"),upload.single("image")];

router.post("/register_categorie",catUpload,c.createCategorie);
router.put("/update_categorie/:id",catUpload,c.updateCategorie);
router.get("/detail_categorie",c.listCategories);
router.delete("/delete_categorie/:id",c.deleteCategorie);
router.get("/prestataires/non_valides",c.prestatairesNonValides);
router.post("/valider_prestataire/:id",c.validerPrestataire);
router.post("/register_prestation",c.createPrestation);
router.put("/update_prestation/:id",c.updatePrestation);
router.get("/detail_prestation",c.listPrestations);
router.delete("/delete_prestation/:id",c.deletePrestation);
router.get("/client/:id",c.prestationsClient);
router.post("/demandes",optionalAuthenticate,c.demandePrestation);
router.get("/prestataire/:id",c.prestataireDashboard);
router.post("/accepter/:id",c.acceptPrestation);
router.get("/prestations_disponibles",c.available);
router.get("/disponibles",c.available);
router.get("/services/:id",c.available);
router.get("/stats/:id",c.stats);
router.get("/note/:id",c.noteMoyenne);
router.get("/avis/:id",c.avis);
router.get("/en_attente",c.enAttente);
router.post("/demande-ciblee",c.createDemandeCiblee);
router.get("/recues/:id",c.demandesRecues);
router.get("/refuses/:id",c.refusees);
router.post("/refuser_prestation/:id",c.refusePrestation);
router.get("/refusees/toutes",c.refusees);
router.get("/terminees/:id",c.termineesParPrestataire);
router.post("/envoyer-demande",authenticate,c.envoyerDemande);
router.post("/repondre-demande/:id",authenticate,c.repondreDemande);
router.get("/notifications",authenticate,c.notifications);
router.post("/notifications/lue/:id",authenticate,c.markNotificationRead);
router.post("/notifications/tous_lues",authenticate,c.markAllRead);
router.delete("/notifications/supprimer/:id",authenticate,c.deleteNotification);
router.get("/prestations_avec_prix",c.avecPrix);

module.exports=router;